# Generated by Django 4.2.4 on 2023-08-16 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restourant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_favorites',
            old_name='track',
            new_name='product',
        ),
    ]
