# Generated by Django 4.2.4 on 2023-08-16 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restourant', '0002_rename_track_product_favorites_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_favorites',
            old_name='user',
            new_name='email',
        ),
    ]
