# Generated by Django 4.2.4 on 2023-08-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='rating',
            field=models.IntegerField(blank=True, choices=[('1', '⭐️'), ('2', '⭐️⭐️'), ('3', '⭐️⭐️⭐️'), ('4', '⭐️⭐️⭐️⭐️'), ('5', '⭐️⭐️⭐️⭐️⭐️')], null=True),
        ),
    ]
